# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: character-sheet-creator
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - 3306:3306